import json

MODEL = "gpt-4o-mini-2024-07-18"

CONTENT_TYPES = {
    "h1": {"max_tokens": 4, "description": "Main Heading for the home page"},
    "h2": {"max_tokens": 12, "description": "Subheading for the home page"},
    "h3": {"max_tokens": 8, "description": "Sub-subheading for the home page"},
    "p": {"max_tokens": 20, "description": "Paragraph for the home page"},
}

PERSONA_STAGES = {
    "First-time homebuyer": [
        "Awareness",
        "Research",
        "Consideration",
        "Evaluation",
        "Purchase",
        "Post-Purchase Support",
        "Ownership",
        "Loyalty",
        "Evangelism",
    ],
    "Real estate investor": [
        "Awareness",
        "Consideration",
        "Evaluation",
        "Capture Lead Information",
        "Showcase Investment Opportunities",
        "Provide Educational Content",
        "Implement Call-to-Action (CTA) Buttons",
        "Trust Signals",
        "Purchase",
        "Ownership",
        "Loyalty",
        "Evangelism",
    ],
    "Luxury homebuyer": [
        "Awareness",
        "Consideration",
        "Evaluation",
        "Purchase",
        "Ownership",
        "Loyalty",
        "Evangelism",
        "Post-Purchase Engagement",
        "Referral",
    ],
    "Renters": [
        "Awareness",
        "Discovery",
        "Consideration",
        "Evaluation",
        "Application",
        "Purchase/Lease Agreement",
        "Move-in",
        "Ownership",
        "Loyalty",
        "Feedback/Review",
        "Evangelism",
        "Repeat Engagement",
    ],
    "Relocating families": [
        "Awareness",
        "Consideration",
        "Evaluation",
        "Purchase",
        "Ownership",
        "Loyalty",
        "Evangelism",
        "Post-Move Support",
    ],
    "Downsizers": [
        "Awareness",
        "Consideration",
        "Evaluation",
        "Personalized Consultation",
        "Purchase",
        "Ownership",
        "Post-Purchase Support",
        "Loyalty",
        "Evangelism",
    ],
    "Vacation home buyer": [
        "Awareness",
        "Consideration",
        "Research",
        "Evaluation",
        "Decision",
        "Purchase",
        "Ownership",
        "Post-Purchase Follow-up",
        "Loyalty",
        "Evangelism",
    ],
    "Commercial property seeker": [
        "Awareness: Discovering the need for commercial space and becoming aware of various online listings.",
        "Consideration: Evaluating different properties and websites, and exploring options like virtual tours and brochures.",
        "Evaluation: Comparing specific listings, using contact forms to request more information, and reading reviews or testimonials.",
        "Purchase: Making the decision to lease or buy a commercial space, involving direct communication for final negotiation.",
        "Ownership: Engaging with property management for setup, maintenance, and support.",
        "Loyalty: Signing up for newsletters with market updates and property tips, and providing feedback.",
        "Evangelism: Recommending the website to others and sharing experiences in business networks.",
    ],
}
